# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170907_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='status',
        ),
    ]
